server:
  port: 8762
  servlet:
    context-path: /api/service-discovery

eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/api/service-discovery/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 20000