management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    config:
      discovery:
        service-id: configserver
        enabled: true
      fail-fast: true
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888/api/config-server
server:
  port: 8085