management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8086

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 'localhost:9092'
      bindings:
        springCloudBusInput:
          group: ${spring.application.name}-spring-cloud-bus
    bus:
      destination: app-cloud-bus