management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888
  servlet:
    context-path: /api/config-server
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/DRodrigoBL/config-files-repo.git'
          search-paths: '{application}'
          default-label: master
    stream:
      kafka:
        binder:
          brokers: 'localhost:9092'
      bindings:
        springCloudBusInput:
          group: ${spring.application.name}-spring-cloud-bus
    bus:
      enabled: true
      destination: app-cloud-bus